#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  liftRight,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  liftLeft,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftFront,     tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMiddle,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           liftLeftTop,   tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           liftLeftBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRightTop,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           liftRightBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightBack,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightMiddle,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rightFront,    tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "functions.c"
#include "pid.c"

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous() {
	driveKp = 0.3;
	driveKi = 0.05;
	driveKd = 0.0;
	startTask(drivePID);
	go(24);
}

task usercontrol() {
	startTask(liftPID);

	while (true) {
		arcadeDrive();
		liftControl();
	}
}
